### ISSUE TITLE
How can I increase the indicator width

### ISSUE THREAD

**Issue by soumyamahunt** [epv44/EVTopTabBar#5]
I want to make the indicator width same as tab item width, how do I do that??

**Comment by epv44** [comment]
This isn't something I currently support. Maybe in a future iteration, although I haven't had much time recently :(

**Comment by epv44** [comment]
I added an `IndicatorLayoutStyle` enum so that you can now toggle if you want a set width (that you can set), if you want it to be the width of the text in the UIButton title label, or the button (tab) width itself.
```
// In your code
// You most likely want .textWidth or .buttonWidth for your use case
 topTabBar = EVPageViewTopTabBar(for: .four, withIndicatorStyle: .textWidth)


// Enum I added
public enum IndicatorLayoutStyle {
    case setWidth(CGFloat), textWidth, buttonWidth
}
```
